### ISSUE TITLE
Logo Design For the App

### ISSUE THREAD

**Issue by ritiksoni00** [HakinCodes/CodeAsylums-App#10]
ill work on this myself! first come first serve! sorry Guys I'm participant too

**Comment by ashishsahu1** [comment]
May I work in this @ritiksoni00

**Comment by ritiksoni00** [comment]
sorry but I'm also the participant so!

**Comment by sayashchaudhary** [comment]
I can design the logo using Adobe illustrator and photoshop, please assign this task to me

**Comment by rungta-ayush** [comment]
@all I am not sure if there is any need for logo design here.
Since this is a project to make an app for codeasylum , we can surely use the official code-asylum logo and other tiles.
This is my kind of take on this.
II think we should confirm once with the *@mentor*, before starting to work on it.

**Comment by helios1101** [comment]
Hey Everyone, 
Great to see such enthusiasm.
But actually the motive to make app based on the website https://www.codeasylums.com. We already have assest ready for everything. 
Closing this issue.
Thanks for this thought contribution. :)
